### PR TITLE
Verify Signature

### PR DESCRIPTION
**Pull request by amiruljack**

### CODE REVIEW

**Comment by suhz** [comment]
Thanks @amiruljack, I don't use billplz anymore so the plugin isn't maintained since then.

Have you tested if it's working? I'll approve the merge and release it to npmjs

**Comment by suhz** [comment]
Until someone has time to test and confirm if this is working, this will remain open.

**Comment by amiruljack** [comment]
> Until someone has time to test and confirm if this is working, this will remain open.

Its working, i am using it for several projects.

**Comment by amiruljack** [comment]
> Thanks @amiruljack, I don't use billplz anymore so the plugin isn't maintained since then.
> 
> Have you tested if it's working? I'll approve the merge and release it to npmjs

Yes. The origin repo is not working, thats why i make changes in the first place..

**Comment by amiruljack** [comment]
Hold on, when im using itm i use it like this, I will make some changes on the codes and resend a new PR

const transactionID = await new Promise<string>( (resolve, reject) => {
    billplz.create_bill(parameter, function(err, res) {
      if (err) {
        reject(new Error("Billplz Error");
      }
      resolve(res.id);
    });
  }).catch(function(e) {
    throw (e);
  });

**Pull request closed without merging**
